name: Contract Pact testing
run-name: Pipeline - from user @${{ github.actor }}

on:
  push:
    branches:
      - master
  
  pull_request:
    types:
      - opened
      - closed
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3  
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
        shell: bash

      - name: Test consumer
        run: |
          npm run test:consumer

      - name: Test provider
        run: npm run test:provider

      

