name: Contract Pact testing
run-name: Pipeline - from user @${{ github.actor }}

on:
  push:
    branches:
      - master
  
  pull_request:
    types:
      - opened
      - closed
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      # - name: Start containers
      #   run: |
      #     sudo docker-compose up -d

      # - name: Wait until containers are done
      #   run: sleep 10

      - name: Test consumer
        run: |
          chmod 777 /opt/hostedtoolcache/node/18.16.0/x64/lib/node_modules/npm/node_modules/@npmcli/run-script/lib/node-gyp-bin 
          npm run test:consumer

      # - name: Publish contract
      #   run: npm run publish:contract

      - name: Test provider
        run: npm run test:provider

      

